language: node_js
node_js:
  - "8.9.2"
addons:
    code_climate:
        repo_token: 6aeeb064603cd3e78f08fb6dac4a93f46ab570b94a08ee2b84011b981300c799 
before_script:
  - cp ./config/server.example.json ./config/server.json
after_script:
  - codeclimate-test-reporter < lcov.info
